### ISSUE TITLE
WCMp admin backend, vendor's issue

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/wcmp-advance-shipping#5]
Admin > WCMP > Vendors > Edit > . The expected/hopeful visuals would show the Policies each Seller has written as part of their store per Seller. We can see the Storefront settings, but not the Policies. Is this possible to show?

Src: https://wc-marketplace.com/support-forum/topic/admin-wcmp-vendors/#post-104512

**Comment by abiarnoldmichael** [comment]
Hi, we have the same issue as above. How can we fix this?
